spring:
  application:
    name: "Eureka"

server:
  port: 8761

# -- Eureka
eureka:
  server:
    enable-self-preservation: true
    response-cache-update-interval-ms: 3000
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    hostname: "localhost"
  client:
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
